import { Asap } from "next/font/google";
import Header from "@/components/layout/header";
import "@/scss/base/main.scss";
import "./globals.css";

const inter = Asap({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
