import { Abel } from "next/font/google";
import Header from "@/components/layout/header";
import "@/scss/base/main.scss";
import "./globals.css";
import Footer from "@/components/layout/footer";

const inter = Abel({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
